#!/usr/bin/python3
this is the sixth task, python's exceptions
